### PR TITLE
Add ".asciidoc" as acceptable file suffix

### PR DESCRIPTION
**Pull request by nikolausschueler**

### CODE REVIEW

**Comment by nikolausschueler** [comment]
I use the ".asciidoc" suffix for a lot of my files and so I suggest to make it an accepted suffix.

I could not find a test for legal (and illegal file suffixes), so no test for suffix ".asciidoc" added. If you think we could need such tests, I will try to come up with an appropriate test.

**Comment by saneef** [comment]
I'll look into this. Shouldn't be hard to support that.

**Comment by saneef** [comment]
I have added support for `.asciidoc` and `.ad` in the new release, [v4.0](https://github.com/saneef/eleventy-plugin-asciidoc/releases/tag/v4.0.0). Please do try out the release.

**Comment by nikolausschueler** [comment]
Hi Saneef,

thanks for accepting my suggestion. I'm currenty using the plugin on a few projects, so far with no problems.

BR

Nik

**Pull request closed without merging**
